import type { ESLint } from 'eslint';

const rules = {
  'import-x/consistent-type-specifier-style': 'error',
  'import-x/default': 'error',
  'import-x/dynamic-import-chunkname': 'off',
  'import-x/export': 'error',
  'import-x/exports-last': 'error',
  'import-x/extensions': 'error',
  'import-x/first': 'error',
  'import-x/group-exports': 'error',
  'import-x/max-dependencies': 'error',
  'import-x/named': 'error',
  'import-x/namespace': 'error',
  'import-x/newline-after-import': 'error',
  'import-x/no-absolute-path': 'error',
  'import-x/no-amd': 'error',
  'import-x/no-anonymous-default-export': 'error',
  'import-x/no-commonjs': 'error',
  'import-x/no-cycle': 'error',
  'import-x/no-default-export': 'off',
  'import-x/no-deprecated': 'error',
  'import-x/no-duplicates': 'error',
  'import-x/no-dynamic-require': 'error',
  'import-x/no-empty-named-blocks': 'error',
  'import-x/no-extraneous-dependencies': 'off',
  'import-x/no-import-module-exports': 'error',
  'import-x/no-internal-modules': 'off',
  'import-x/no-mutable-exports': 'error',
  'import-x/no-named-as-default': 'error',
  'import-x/no-named-as-default-member': 'error',
  'import-x/no-named-default': 'error',
  'import-x/no-named-export': 'off',
  'import-x/no-namespace': 'error',
  'import-x/no-nodejs-modules': 'off',
  'import-x/no-relative-packages': 'error',
  'import-x/no-relative-parent-imports': 'off',
  'import-x/no-rename-default': 'error',
  'import-x/no-restricted-paths': 'off',
  'import-x/no-self-import': 'error',
  'import-x/no-unassigned-import': 'error',
  'import-x/no-unresolved': 'error',
  'import-x/no-unused-modules': 'error',
  'import-x/no-useless-path-segments': 'error',
  'import-x/no-webpack-loader-syntax': 'error',
  'import-x/order': 'off',
  'import-x/prefer-default-export': 'error',
  'import-x/prefer-namespace-import': 'off',
  'import-x/unambiguous': 'error'
} as const satisfies ESLint.ConfigData['rules'];

export default rules;
