import type { ESLint } from 'eslint';

const rules = {
  'jsdoc/check-access': 'error',
  'jsdoc/check-alignment': 'error',
  'jsdoc/check-examples': 'off',
  'jsdoc/check-indentation': 'error',
  'jsdoc/check-line-alignment': 'off',
  'jsdoc/check-param-names': 'error',
  'jsdoc/check-property-names': 'error',
  'jsdoc/check-syntax': 'error',
  'jsdoc/check-tag-names': 'error',
  'jsdoc/check-template-names': 'error',
  'jsdoc/check-types': 'error',
  'jsdoc/check-values': 'error',
  'jsdoc/convert-to-jsdoc-comments': 'off',
  'jsdoc/empty-tags': 'error',
  'jsdoc/implements-on-classes': 'error',
  'jsdoc/imports-as-dependencies': 'error',
  'jsdoc/informative-docs': 'error',
  'jsdoc/lines-before-block': 'error',
  'jsdoc/match-description': 'error',
  'jsdoc/match-name': 'off',
  'jsdoc/multiline-blocks': 'error',
  'jsdoc/no-bad-blocks': 'error',
  'jsdoc/no-blank-block-descriptions': 'error',
  'jsdoc/no-blank-blocks': 'error',
  'jsdoc/no-defaults': 'error',
  'jsdoc/no-missing-syntax': ['off', { contexts: [] }],
  'jsdoc/no-multi-asterisks': 'error',
  'jsdoc/no-restricted-syntax': 'off',
  'jsdoc/no-types': 'off',
  'jsdoc/no-undefined-types': 'error',
  'jsdoc/prefer-import-tag': 'off',
  'jsdoc/reject-any-type': 'error',
  'jsdoc/reject-function-type': 'error',
  'jsdoc/require-asterisk-prefix': 'error',
  'jsdoc/require-description': 'off',
  'jsdoc/require-description-complete-sentence': 'error',
  'jsdoc/require-example': 'off',
  'jsdoc/require-file-overview': 'off',
  'jsdoc/require-hyphen-before-param-description': 'error',
  'jsdoc/require-jsdoc': 'off',
  'jsdoc/require-next-description': 'off',
  'jsdoc/require-next-type': 'error',
  'jsdoc/require-param': 'error',
  'jsdoc/require-param-description': 'error',
  'jsdoc/require-param-name': 'error',
  'jsdoc/require-param-type': 'error',
  'jsdoc/require-property': 'error',
  'jsdoc/require-property-description': 'error',
  'jsdoc/require-property-name': 'error',
  'jsdoc/require-property-type': 'error',
  'jsdoc/require-returns': 'error',
  'jsdoc/require-returns-check': 'error',
  'jsdoc/require-returns-description': 'error',
  'jsdoc/require-returns-type': 'error',
  'jsdoc/require-tags': 'off',
  'jsdoc/require-template': 'error',
  'jsdoc/require-throws': 'error',
  'jsdoc/require-throws-description': 'off',
  'jsdoc/require-throws-type': 'error',
  'jsdoc/require-yields': 'error',
  'jsdoc/require-yields-check': 'error',
  'jsdoc/require-yields-description': 'off',
  'jsdoc/require-yields-type': 'error',
  'jsdoc/sort-tags': 'error',
  'jsdoc/tag-lines': [
    'error',
    'never',
    { startLines: 1 }
  ],
  'jsdoc/text-escaping': ['error', { escapeHTML: true }],
  'jsdoc/type-formatting': 'error',
  'jsdoc/valid-types': 'error'
} as const satisfies ESLint.ConfigData['rules'];

export default rules;
