language: node_js
node_js:
- node
- lts/carbon
- lts/boron
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: egy186@yahoo.co.jp
  api_key:
    secure: Y99ggWqoU+zgWV5BtYSd/PR7D46ChBfGZ+cyMU0tleCsBLc8BOX7QE6alQ8IYzXKpeZPk9Larl4Q2HaYGiHryw51OFugiIE5r1q1/xgD6GNPNWocTL72K2lPwTwQdUC8g+6uIWqP6hAfd2kmTc3pLi4Ac8BQeBTjpYpg7t2kP0jsvJXSKB1fVH9FP5abKGebo2NmbN3VSZFybJC5QD+xeZX6iM99lzg7QCXxv3ztW4BdMs1WmhiiUQilxUBnmNtKE8upnsA8ovELGrLx8NmG5HYd0UMdTGcYo7b5TGZi9P3Ud6GdhLfB2rgv4saFgtjIg/YbSpE8B4csS+ZZfTIAMPwy4Tm7nYHBRvKeQIqR/xomKjfIcluIejL2mwE5aj+HKXEpMyzMXWq/AV1eT7u4ZJ0T4lJp0kZHJVIe4hcnomZsI7UqdJ1PMhTO+hwQkfiWjaChiQiA9/Zy9w1XResZqkQFHhXi8unAh+z8rnFX4uChozj9FymLgSXWXobpVO/0Zu3dN7sa6WPswwuZo/nR202YEHDicxIy4NBoOTDzVzugHO3/QIeRn/VYUf7cMHLVbvZps+EVUi7G+0J1tlM1g66SxT4dyKskJjdqTfikb5QntmB2zBw1n2YtoyCF5RcfLez3L2nQzlkN6QCPeJ/EJ4IUqn0RL0HZF24OB4hk1pk=
  on:
    tags: true
    repo: egy186/eslint-config
