import type { ESLint, Linter } from 'eslint';
import eslintReact from '@eslint-react/eslint-plugin';
import reactHooksPlugin from 'eslint-plugin-react-hooks';

const config = {
  files: ['**/*.{jsx,tsx}'],
  languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
  plugins: {
    '@eslint-react': eslintReact,
    'react-hooks': reactHooksPlugin as ESLint.Plugin
  },
  rules: {
    '@eslint-react/dom-no-dangerously-set-innerhtml': 'error',
    '@eslint-react/dom-no-dangerously-set-innerhtml-with-children': 'error',
    '@eslint-react/dom-no-find-dom-node': 'error',
    '@eslint-react/dom-no-hydrate': 'error',
    '@eslint-react/dom-no-missing-iframe-sandbox': 'error',
    '@eslint-react/dom-no-render': 'error',
    '@eslint-react/dom-no-render-return-value': 'error',
    '@eslint-react/dom-no-script-url': 'error',
    '@eslint-react/dom-no-string-style-prop': 'error',
    '@eslint-react/dom-no-unknown-property': ['error', { requireDataLowercase: true }],
    '@eslint-react/dom-no-unsafe-target-blank': 'error',
    '@eslint-react/dom-no-void-elements-with-children': 'error',
    '@eslint-react/jsx-no-children-prop': 'error',
    '@eslint-react/jsx-no-comment-textnodes': 'error',
    '@eslint-react/jsx-no-namespace': 'error',
    '@eslint-react/jsx-no-useless-fragment': 'error',
    '@eslint-react/no-access-state-in-setstate': 'error',
    '@eslint-react/no-array-index-key': 'error',
    '@eslint-react/no-component-will-mount': 'error',
    '@eslint-react/no-component-will-receive-props': 'error',
    '@eslint-react/no-component-will-update': 'error',
    '@eslint-react/no-create-ref': 'error',
    '@eslint-react/no-direct-mutation-state': 'error',
    '@eslint-react/no-duplicate-key': 'error',
    '@eslint-react/no-forward-ref': 'error',
    '@eslint-react/no-implicit-key': 'error',
    '@eslint-react/no-leaked-conditional-rendering': 'error',
    '@eslint-react/no-missing-component-display-name': 'error',
    '@eslint-react/no-missing-context-display-name': 'error',
    '@eslint-react/no-missing-key': 'error',
    '@eslint-react/no-nested-component-definitions': 'error',
    '@eslint-react/no-set-state-in-component-did-update': 'error',
    '@eslint-react/no-set-state-in-component-will-update': 'error',
    '@eslint-react/no-unsafe-component-will-mount': 'error',
    '@eslint-react/no-unsafe-component-will-receive-props': 'error',
    '@eslint-react/no-unsafe-component-will-update': 'error',
    '@eslint-react/no-unstable-context-value': 'error',
    '@eslint-react/no-unstable-default-props': 'error',
    '@eslint-react/no-unused-class-component-members': 'error',
    '@eslint-react/no-unused-props': 'error',
    '@eslint-react/no-unused-state': 'error',
    '@eslint-react/use-state': 'error',
    'max-lines-per-function': ['warn', 100],
    'react-hooks/capitalized-calls': 'off',
    'react-hooks/config': 'error',
    'react-hooks/error-boundaries': 'error',
    'react-hooks/exhaustive-deps': 'error',
    'react-hooks/exhaustive-effect-dependencies': 'error',
    'react-hooks/fbt': 'off',
    'react-hooks/gating': 'error',
    'react-hooks/globals': 'error',
    'react-hooks/hooks': 'off',
    'react-hooks/immutability': 'error',
    'react-hooks/incompatible-library': 'error',
    'react-hooks/invariant': 'off',
    'react-hooks/memo-dependencies': 'error',
    'react-hooks/memoized-effect-dependencies': 'off',
    'react-hooks/no-deriving-state-in-effects': 'off',
    'react-hooks/preserve-manual-memoization': 'error',
    'react-hooks/purity': 'error',
    'react-hooks/refs': 'error',
    'react-hooks/rule-suppression': 'off',
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/set-state-in-effect': 'error',
    'react-hooks/set-state-in-render': 'error',
    'react-hooks/static-components': 'error',
    'react-hooks/syntax': 'off',
    'react-hooks/todo': 'off',
    'react-hooks/unsupported-syntax': 'error',
    'react-hooks/use-memo': 'error',
    'react-hooks/void-use-memo': 'error'
  }
} as const satisfies Linter.Config;

export { config as react };

export default config;
