import type { ESLint, Linter } from 'eslint';
import eslintReact from '@eslint-react/eslint-plugin';
import reactHooksPlugin from 'eslint-plugin-react-hooks';

const config = {
  files: ['**/*.{jsx,tsx}'],
  languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
  plugins: {
    '@eslint-react': eslintReact,
    'react-hooks': reactHooksPlugin as ESLint.Plugin
  },
  rules: {
    '@eslint-react/dom-no-dangerously-set-innerhtml': 'error',
    '@eslint-react/dom-no-dangerously-set-innerhtml-with-children': 'error',
    '@eslint-react/dom-no-find-dom-node': 'error',
    '@eslint-react/dom-no-flush-sync': 'error',
    '@eslint-react/dom-no-hydrate': 'error',
    '@eslint-react/dom-no-missing-button-type': 'error',
    '@eslint-react/dom-no-missing-iframe-sandbox': 'error',
    '@eslint-react/dom-no-render': 'error',
    '@eslint-react/dom-no-render-return-value': 'error',
    '@eslint-react/dom-no-script-url': 'error',
    '@eslint-react/dom-no-string-style-prop': 'error',
    '@eslint-react/dom-no-unknown-property': ['error', { requireDataLowercase: true }],
    '@eslint-react/dom-no-unsafe-iframe-sandbox': 'error',
    '@eslint-react/dom-no-unsafe-target-blank': 'error',
    '@eslint-react/dom-no-use-form-state': 'error',
    '@eslint-react/dom-no-void-elements-with-children': 'error',
    '@eslint-react/error-boundaries': 'off',
    '@eslint-react/exhaustive-deps': 'error',
    '@eslint-react/globals': 'off',
    '@eslint-react/immutability': 'off',
    '@eslint-react/jsx-no-children-prop': 'error',
    '@eslint-react/jsx-no-children-prop-with-children': 'error',
    '@eslint-react/jsx-no-comment-textnodes': 'error',
    '@eslint-react/jsx-no-key-after-spread': 'error',
    '@eslint-react/jsx-no-leaked-dollar': 'error',
    '@eslint-react/jsx-no-leaked-semicolon': 'error',
    '@eslint-react/jsx-no-namespace': 'error',
    '@eslint-react/jsx-no-useless-fragment': 'error',
    '@eslint-react/naming-convention-context-name': 'error',
    '@eslint-react/naming-convention-id-name': 'error',
    '@eslint-react/naming-convention-ref-name': 'error',
    '@eslint-react/no-access-state-in-setstate': 'error',
    '@eslint-react/no-array-index-key': 'error',
    '@eslint-react/no-children-count': 'error',
    '@eslint-react/no-children-for-each': 'error',
    '@eslint-react/no-children-map': 'error',
    '@eslint-react/no-children-only': 'error',
    '@eslint-react/no-children-to-array': 'error',
    '@eslint-react/no-class-component': 'error',
    '@eslint-react/no-clone-element': 'error',
    '@eslint-react/no-component-will-mount': 'error',
    '@eslint-react/no-component-will-receive-props': 'error',
    '@eslint-react/no-component-will-update': 'error',
    '@eslint-react/no-context-provider': 'error',
    '@eslint-react/no-create-ref': 'error',
    '@eslint-react/no-direct-mutation-state': 'error',
    '@eslint-react/no-duplicate-key': 'error',
    '@eslint-react/no-forward-ref': 'error',
    '@eslint-react/no-implicit-children': 'error',
    '@eslint-react/no-implicit-key': 'error',
    '@eslint-react/no-implicit-ref': 'error',
    '@eslint-react/no-leaked-conditional-rendering': 'error',
    '@eslint-react/no-missing-component-display-name': 'error',
    '@eslint-react/no-missing-context-display-name': 'error',
    '@eslint-react/no-missing-key': 'error',
    '@eslint-react/no-misused-capture-owner-stack': 'error',
    '@eslint-react/no-nested-component-definitions': 'error',
    '@eslint-react/no-nested-lazy-component-declarations': 'error',
    '@eslint-react/no-set-state-in-component-did-mount': 'error',
    '@eslint-react/no-set-state-in-component-did-update': 'error',
    '@eslint-react/no-set-state-in-component-will-update': 'error',
    '@eslint-react/no-unnecessary-use-prefix': 'error',
    '@eslint-react/no-unsafe-component-will-mount': 'error',
    '@eslint-react/no-unsafe-component-will-receive-props': 'error',
    '@eslint-react/no-unsafe-component-will-update': 'error',
    '@eslint-react/no-unstable-context-value': 'error',
    '@eslint-react/no-unstable-default-props': 'error',
    '@eslint-react/no-unused-class-component-members': 'error',
    '@eslint-react/no-unused-props': 'error',
    '@eslint-react/no-unused-state': 'error',
    '@eslint-react/no-use-context': 'error',
    '@eslint-react/purity': 'off',
    '@eslint-react/refs': 'off',
    '@eslint-react/rsc-function-definition': 'error',
    '@eslint-react/rules-of-hooks': 'error',
    '@eslint-react/set-state-in-effect': 'off',
    '@eslint-react/set-state-in-render': 'off',
    '@eslint-react/static-components': 'off',
    '@eslint-react/unsupported-syntax': 'off',
    '@eslint-react/use-memo': 'off',
    '@eslint-react/use-state': 'error',
    '@eslint-react/web-api-no-leaked-event-listener': 'error',
    '@eslint-react/web-api-no-leaked-fetch': 'error',
    '@eslint-react/web-api-no-leaked-intersection-observer': 'error',
    '@eslint-react/web-api-no-leaked-interval': 'error',
    '@eslint-react/web-api-no-leaked-resize-observer': 'error',
    '@eslint-react/web-api-no-leaked-timeout': 'error',
    'max-lines-per-function': ['warn', 100],
    'react-hooks/capitalized-calls': 'off',
    'react-hooks/config': 'error',
    'react-hooks/error-boundaries': 'error',
    'react-hooks/exhaustive-deps': 'error',
    'react-hooks/exhaustive-effect-dependencies': 'error',
    'react-hooks/fbt': 'off',
    'react-hooks/gating': 'error',
    'react-hooks/globals': 'error',
    'react-hooks/hooks': 'off',
    'react-hooks/immutability': 'error',
    'react-hooks/incompatible-library': 'error',
    'react-hooks/invariant': 'off',
    'react-hooks/memo-dependencies': 'error',
    'react-hooks/memoized-effect-dependencies': 'off',
    'react-hooks/no-deriving-state-in-effects': 'off',
    'react-hooks/preserve-manual-memoization': 'error',
    'react-hooks/purity': 'error',
    'react-hooks/refs': 'error',
    'react-hooks/rule-suppression': 'off',
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/set-state-in-effect': 'error',
    'react-hooks/set-state-in-render': 'error',
    'react-hooks/static-components': 'error',
    'react-hooks/syntax': 'off',
    'react-hooks/todo': 'off',
    'react-hooks/unsupported-syntax': 'error',
    'react-hooks/use-memo': 'error',
    'react-hooks/void-use-memo': 'error'
  },
  settings: {
    'import-x/extensions': [
      '.js',
      '.jsx',
      '.mjs',
      '.cjs'
    ]
  }
} as const satisfies Linter.Config;

export { config as react };

export default config;
